# -*- coding: utf-8 -*-
"""Ex2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Mf-cXTo_hhf8LMLS4ViB3mbxDBSADP4K
"""

# a)
import pandas as pd
from google.colab import files
import matplotlib.pyplot as plt

uploaded = files.upload()


caminho_arquivo = list(uploaded.keys())[0]


dados = pd.read_excel(caminho_arquivo, sheet_name="Pedidos de Asilo")

dados['Número de Pedidos'] = pd.to_numeric(dados['Número de Pedidos'], errors='coerce')


print("Dimensões do DataFrame:", dados.shape)
print("Linhas iniciais do DataFrame:")
print(dados.head(10))

# b)
plt.figure(figsize=(10, 6))
plt.hist(
    dados["Número de Pedidos"].dropna(),
    bins=100,
    range=(0, 100),
    color="#003b64",
    edgecolor="black",
    alpha=0.7
)


plt.title("Distribuição do Número de Pedidos de Asilo")
plt.xlabel("Número de Pedidos")
plt.ylabel("Frequência")
plt.grid(True)
plt.xlim(0, 100)


plt.show()

# c)
plt.figure(figsize=(12, 6))
plt.scatter(
    dados["Ano"],
    dados["Número de Pedidos"],
    color="#003b64",
    alpha=0.5,
    s=10,
)


plt.title("Número de Pedidos de Asilo ao Longo dos Anos")
plt.xlabel("Ano")
plt.ylabel("Número de Pedidos")
plt.grid(True)


plt.show()